export const skillsData = [
    //programmingLanguages
    "Abap",
    "Ada",
    "C/C++",
    "C#",
    "Cobol",
    "Dart",
    "Delphi",
    "Go",
    "Groovy",
    "Haskell",
    "Julia",
    "Kotlin",
    "Java",
    "Javascript",
    "Lua",
    "Matlab",
    "Objective-C",
    "Perl",
    "PHP",
    "Python",
    "R",
    "Ruby",
    "Rust",
    "Scala",
    "Swift",
    "TypeScript",
    "VBA",
    "Visual Basic",
    //webDevelopmentSkills
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "ASP.NET",
    "Ruby on Rails",
    "Django",
    "Flask",
    "Laravel",
    "Spring Boot",

    //databaseskills
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Oracle",
    "Microsoft SQL Server",
    "SQLite",
    "Firebase",
    "Cassandra",
    "Redis",
    "Elasticsearch",
    "DynamoDB",
    "Neo4j",
    "MariaDB",
    "Couchbase",
    "Amazon RDS",
    "Hadoop",
    "Apache Cassandra",
    "Apache HBase",
    "Apache CouchDB",
    "Amazon DynamoDB",
    "Google Cloud Firestore",
    "Apache Kafka",
    "Riak",
    "ArangoDB",

    //AIML skills
    "Artificial Intelligence(AI)",
    "Machine Learning(ML)",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Data Mining",
    "TensorFlow",
    "Data Science",
    "Big Data",
    "SciPy",
    "NumPy",

    //Common skills
    "Communication skills",
    "Problem-solving skills",
    "Time management",
    "Adaptability",
    "Teamwork",
    "Critical thinking",
    "Leadership",
    "Analytical skills",
    "Organizational skills",
    "Initiative",
];
